---

- name: changing apache main config ServerAdmin
  lineinfile:
    line: 'ServerAdmin {{ apache_server_admin }}'
    regexp: 'ServerAdmin root@localhost'
    backrefs: yes
    path: '{{ apache_config_file }}'
  register: httpd_configuration_serveradmin
  when: apache_virtual_hostname != ''

- name: changing apache main config ServerName
  lineinfile:
    line: 'ServerName {{ apache_virtual_hostname }}'
    regexp: '#ServerName '
    backrefs: yes
    path: '{{ apache_config_file }}'
  register: httpd_configuration_servername
  when: apache_virtual_hostname != ''

- name: deploying ssl config
  template:
    src: apache-ssl.j2
    dest: '{{ apache_config_dir }}/ssl.conf'
    owner: root
    group: '{{ apache_group }}'
    mode: 0640
  when: apache_use_ssl and (apache_virtual_hostname != '')
  register: httpd_configuration_ssl

- name: restart httpd
  service:
    name: '{{ apache_servicename }}'
    state: restarted
  when: >
    httpd_configuration_serveradmin.changed or
    httpd_configuration_servername.changed or
    httpd_configuration_ssl.changed

...
