---
# change it to apt instead of yum to use it with Debian or else
- name: install apache basic
  apt:
    name: apache # the package may has a different name, too
    state: present

- name: install ssl capability if needed
  apt:
    name: mod_ssl
    state: present
  when: apache_use_ssl

...
