---

- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

# setup/install tasks
- include_tasks: install-RedHat.yml
  when: ansible_os_family = 'RedHat'

- include_tasks: install-Debian.yml
  when: ansible_os_family = 'Debian'

- name: Enroll Configuration
  include_tasks: config.yml

- name: Make sure the daemon works
  include_tasks: service.yml

...
